ADCBoard:
  init: None
  # Sampling rates in samples per seconds (SPS) with respective integer register value
  # See https://github.com/ul-gh/PiPyADC/blob/pigpio/examples/waveshare_board/waveshare_config.py#L249
  drates:
    2.5: 3
    5: 19
    10: 35
    15: 51
    25: 67
    30: 83
    50: 99
    60: 114
    100: 130
    500: 146
    1000: 161
    2000: 176
    3750: 192
    7500: 208
    15000: 224
    30000: 240

IrradDAQBoard:
  init:
    port: /dev/Arduino-Readout-Board
    version: v0.2
    address: 0x20

ScanStage:
  init:
    config: scan_stage.yaml
    port: /dev/Zaber-Controller-X-MCC3
    n_axis: 2
    axis_addrs:
      - 1
      - 2
    invert_axis:
      - 1
    axis_init:
      - step: 0.1953125e-6
        travel: 300.0e-3
        model: LRQ300HL-E01T3A
      - step: 0.1953125e-6
        travel: 300.0e-3
        model: LRQ300HL-E01T3A
  motorstage: True

SetupTableStage:
  init:
    config: setup_table_stage.yaml
    port: /dev/Zaber-Controller-X-MCC3
    axis_addr: 3
    step: 0.1953125e-6
    travel: 284.0e-3
    model: LRQ300HL-E01T3A
  motorstage: True

ExternalCupStage:
  init:
    config: external_cup_stage.yaml
    host: localhost
    port: 45000
    udp:
      - 131.220.221.98
      - 8802
    travel: 716.5e-3
    model: ITEM-Linear-Stage
  motorstage: True

ArduinoNTCReadout:
  init:
    port: /dev/Arduino-NTC-Readout
    baudrate: 115200
    timeout: 5
    ntc_lim:
      - -55
      - 125

RadiationMonitor:
  init:
    counter_type: GasCounter
    counter_port: /dev/Arduino-Radiation-Monitor
    hv_port: /dev/ISEG-HV

ArduinoMUX:
  init:
    port: /dev/zero
    baudrate: 115200
    timeout: 5
