# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    name: Testing Python ${{matrix.python-version}} on ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        python-version: ["3.9", "3.10"]

    runs-on: ${{matrix.os}}    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Dependency installation
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Package installation
        run: pip install -e .

      - name: Qt6 default installation
        run: |
          if [[ ${{ matrix.os }} != 'ubuntu-latest' ]]; then
            echo "Adding Qt6 backport for ${{ matrix.os }}"
            sudo add-apt-repository ppa:okirby/qt6-backports
          fi
          sudo apt-get update
          sudo apt-get install qt6-base-dev --fix-missing
        
      - name: Headless display setup
        uses: pyvista/setup-headless-display-action@v1   

      - name: Testing on ref -> ${{github.head_ref || github.ref_name}}
        run: pytest

  install:
    name: Testing install.sh script with Python ${{matrix.python-version}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10"]

    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run install.sh
        run: |
          echo "Installing to $PWD..."
          ./scripts/install.sh --ic_path=$PWD 

      - name: Check installation
        run: |
          source .venv/bin/activate
          irrad_control --help
          irrad_analyse --help
